### ISSUE TITLE
Estudar sobre empacotamento de aplicação em Python Django

### ISSUE THREAD

**Issue by AllanNobre** [Software-Design-2017/SSMais#1]
**Sugestões:**

- [x] Pesquisar como gerar "plug-ins", pois é como a comunidade conhece;
- [x] Criar documento na Wiki para explicar o processo de empacotamento de Aplicação;
- [x] Disponibilizar resultados nessa própria Issue.

**Comment by Ronyell** [comment]
https://github.com/Software-Design-2017/SSMais/wiki/Reutiliza%C3%A7%C3%A3o-de-Aplica%C3%A7%C3%B5es
