### ISSUE TITLE
Criação do módulo Provedor e Recurso

### ISSUE THREAD

**Issue by Ronyell** [Software-Design-2017/SSMais#14]
**Sugestões**

- [x] Criar classe Provedor (frozen spot);
- [x] Definir dados genéricos para o Provedor;
- [x] Criar classe Recurso;
- [x] Criar classe Horário de Funcionamento;
- [x] Criar classe formulários;
- [ ] Criar classe ServiçoRecurso;
- [ ] Estruturar Cliente-SSMais;
- [ ] Especificar se será um frozen-spot, um hot-spot ou core; 
- [ ] Modificar diagrama de classes;

**Comment by thiagonf** [comment]
A classe recurso seria importante pro contexto, mas por causa da necessidade de redução de escopo para entregar o software funcional ela foi cortada.
