### ISSUE TITLE
Estudar sobre encapsulamento em Python Django

### ISSUE THREAD

**Issue by AllanNobre** [Software-Design-2017/SSMais#2]
**Sugestões:**
- [x] Verificar plug in caso a linguagem não dê suporte direto;
- [x] Escrever resultados na própria issue.

**Comment by thiagonf** [comment]
**Fonte:** 
https://docs.python.org/2/tutorial/classes.html#private-variables-and-class-local-references

> 9.6. Private Variables and Class-local References
> “Private” instance variables that cannot be accessed except from inside an object don’t exist in Python. However, there is a convention that is followed by most Python code: a name prefixed with an underscore (e.g. _spam) should be treated as a non-public part of the API (whether it is a function, a method or a data member). It should be considered an implementation detail and subject to change without notice.
